In [1]:
import pandas as pd
import requests

In [2]:
csv_path = "Surf.csv"

In [3]:
surf = pd.read_csv(csv_path, encoding="utf-8")
surf.head()

        spot  longitude  latitude  spot_id
0     Thurso  58.598988 -3.509359       47
1    Fistral  50.416497 -5.099329        1
2     Easkey  54.292499 -8.952585     1501
3  Manorbier  51.642795 -4.803594      993
4  Carbedelo  41.677002 -8.829828      193

In [4]:
surf_cali = surf.loc[(surf['longitude']< 43) & (surf['longitude']>32)]
surf_cali.reset_index(drop=True)

                       spot  longitude    latitude  spot_id
0                 Carbedelo  41.677002   -8.829828      193
1                Supertubos  39.337783   -9.360137      196
2             Jardim do Mar  32.737025  -17.212566      639
3                     Coxos  39.001853   -9.427324     4344
4              Pico da Mota  39.387273   -9.297724     4349
..                      ...        ...         ...      ...
153            Venice Beach  33.984676 -118.470325       58
154            Virgin Creek  39.506398 -123.777649      303
155          Virginia Beach  36.852926  -75.977985      396
156                Wildwood  39.000669  -74.799333      392
157  Zuma Beach County Park  34.021802 -118.831190      853

[158 rows x 4 columns]

In [41]:
surf_cali4 = surf_cali.loc[(surf_cali['latitude']> -123) & (surf_cali['latitude']< -113)]
surf_cali4.reset_index(drop=True)

                         spot  longitude  latitude  spot_id
0                       Ponto     33.088  -117.314     1149
1              Cabrillo Point     33.707  -118.285      284
2                   Haggertys     33.803  -118.401      282
3                 Skunk Point     33.983  -119.984     1251
4                       Secos     34.038  -118.879      278
..                        ...        ...       ...      ...
58                  The Wedge     33.593  -117.881      287
59  Torrey Pines Blacks Beach     32.890  -117.254      295
60                   Trestles     33.385  -117.594      291
61               Venice Beach     33.985  -118.470       58
62     Zuma Beach County Park     34.022  -118.831      853

[63 rows x 4 columns]

In [47]:
surfcali5 = surf_cali4.copy()

In [49]:
surfcali6 = surfcali5.round(3)

In [51]:
surfcali6

                          spot  longitude  latitude  spot_id
41                       Ponto     33.088  -117.314     1149
42              Cabrillo Point     33.707  -118.285      284
43                   Haggertys     33.803  -118.401      282
44                 Skunk Point     33.983  -119.984     1251
45                       Secos     34.038  -118.879      278
..                         ...        ...       ...      ...
258                  The Wedge     33.593  -117.881      287
263  Torrey Pines Blacks Beach     32.890  -117.254      295
265                   Trestles     33.385  -117.594      291
268               Venice Beach     33.985  -118.470       58
277     Zuma Beach County Park     34.022  -118.831      853

[63 rows x 4 columns]

In [52]:
for x, y in zip(surfcali6['latitude'],surfcali6['longitude']):
    print(f'{x}, {y}')

-117.314, 33.088
-118.285, 33.707
-118.401, 33.803
-119.984, 33.983
-118.879, 34.038
-119.303, 34.273
-119.882, 34.409
-120.054, 34.461
-121.121, 35.582
-121.977, 36.596
-122.026, 36.952
-121.972, 36.955
-121.844, 36.288
-119.843, 34.406
-117.32, 33.103
-121.93, 36.552
-120.906, 35.449
-118.96, 34.051
-117.257, 32.796
-122.216, 37.025
-119.917, 34.432
-119.412, 34.338
-118.004, 33.655
-120.501, 34.511
-117.774, 33.535
-122.502, 37.599
-118.194, 33.77
-118.194, 33.77
-118.417, 33.772
-118.8, 34.008
-118.396, 33.885
-121.862, 36.932
-122.537, 37.831
-122.497, 37.496
-117.251, 32.771
-121.114, 35.576
-120.866, 35.392
-120.866, 35.392
-121.791, 36.815
-117.93, 33.619
-117.829, 33.58
-117.251, 32.756
-120.612, 35.099
-117.385, 33.195
-117.258, 32.796
-119.388, 34.319
-118.806, 34.001
-119.407, 34.336
-117.719, 33.477
-117.621, 33.419
-118.5, 34.013
-117.255, 32.864
-118.107, 33.738
-117.142, 32.635
-117.276, 32.996
-117.292, 33.035
-117.273, 32.85
-120.499, 34.508
-117.881, 33.593
-117.254, 32.89
-117.594, 33.385
-118.47, 33.985
-118.831, 34.022

In [13]:
import arrow
import requests

In [54]:
# Get first hour of today
start = arrow.now().floor('day')

# Get last hour of today
end = arrow.now().ceil('day')

response = requests.get(
  'https://api.stormglass.io/v2/weather/point',
  params={
    'lat': 33.707,
    'lng': -118.285,
    'params': ','.join(['waveHeight', 'airTemperature']),
    'start': start.to('UTC').timestamp(),  # Convert to UTC timestamp
    'end': end.to('UTC').timestamp()  # Convert to UTC timestamp
  },
  headers={
    'Authorization': 'd87dfa70-985c-11ed-b59d-0242ac130002-d87dfade-985c-11ed-b59d-0242ac130002'
  }
)

# Do something with response data.
json_data = response.json()

In [78]:
windspeed = []
winddirection = []
waveheight = []
airtemp = []
watertemp = []

url = 'https://api.stormglass.io/v2/weather/point'
for x, y in zip(surfcali6['latitude'], surfcali6['longitude']):
    try:
        lat = (f'{y}')
        lng = (f'{x}')

        params ={
            'lat': lat,
            'lng': lng,
            'params': ','.join(['waveHeight', 'airTemperature', 'windSpeed', 'windDirection', 'waterTemperature']),
            'start': start.to('UTC').timestamp(),  # Convert to UTC timestamp
            'end': end.to('UTC').timestamp()  # Convert to UTC timestamp
        }
        headers ={
        'Authorization': 'd87dfa70-985c-11ed-b59d-0242ac130002-d87dfade-985c-11ed-b59d-0242ac130002'
        }

        response = requests.get(url, params=params, headers=headers)
        json_data3 = response.json()

        windspeed_data = json_data3['hours'][1]['windSpeed']['icon']
        winddirection_data = json_data3['hours'][1]['windDirection']['icon']
        waveheight_data = json_data3['hours'][1]['waveHeight']['icon']
        airtemp_data = json_data3['hours'][1]['airTemperature']['noaa']
        watertemp_data = json_data3['hours'][1]['waterTemperature']['meto']

        windspeed.append(windspeed_data)
        winddirection.append(winddirection_data)
        waveheight.append(waveheight_data)
        airtemp.append(airtemp_data)
        watertemp.append(watertemp_data)

    except:
        print('failed')
        print(f'at {x},{y}')

In [77]:
json_data3['hours'][1]['windDirection']['icon']

24.8

In [79]:
df = pd.DataFrame({"windspeed":windspeed,
                    "winddirection":winddirection,
                    "waveheight":waveheight,
                    "airtemp":airtemp,
                    "watertemp":watertemp

})

In [80]:
df

    windspeed  winddirection  waveheight  airtemp  watertemp
0       3.160        334.280       2.020   12.890     14.990
1       1.770         18.860       1.960   13.460     14.720
2       1.770         18.860       1.960   10.980     14.550
3       7.540        322.750       2.690   12.260     13.410
4       2.310         18.010       1.980   10.580     14.390
..        ...            ...         ...      ...        ...
58      1.520        336.980       1.960   12.760     14.830
59      3.160        334.280       2.020   12.890     14.990
60      1.940        341.230       1.860    9.150     14.910
61      1.770         18.860       1.960   10.980     14.380
62      3.400         24.800       1.790   10.580     14.420

[63 rows x 5 columns]

In [81]:
surfcali6.reset_index(inplace=True)
surfcali6

    index                       spot  longitude  latitude  spot_id
0      41                      Ponto     33.088  -117.314     1149
1      42             Cabrillo Point     33.707  -118.285      284
2      43                  Haggertys     33.803  -118.401      282
3      44                Skunk Point     33.983  -119.984     1251
4      45                      Secos     34.038  -118.879      278
..    ...                        ...        ...       ...      ...
58    258                  The Wedge     33.593  -117.881      287
59    263  Torrey Pines Blacks Beach     32.890  -117.254      295
60    265                   Trestles     33.385  -117.594      291
61    268               Venice Beach     33.985  -118.470       58
62    277     Zuma Beach County Park     34.022  -118.831      853

[63 rows x 5 columns]

In [82]:
combined = surfcali6.join(df, how='left')

In [83]:
combined

,index,spot,longitude,latitude,spot_id,windspeed,winddirection,waveheight,airtemp,watertemp
0,41,Ponto,33.088,-117.314,1149,3.160,334.280,2.020,12.890,14.990
1,42,Cabrillo Point,33.707,-118.285,284,1.770,18.860,1.960,13.460,14.720
2,43,Haggertys,33.803,-118.401,282,1.770,18.860,1.960,10.980,14.550
3,44,Skunk Point,33.983,-119.984,1251,7.540,322.750,2.690,12.260,13.410
4,45,Secos,34.038,-118.879,278,2.310,18.010,1.980,10.580,14.390
...,...,...,...,...,...,...,...,...,...,...
58,258,The Wedge,33.593,-117.881,287,1.520,336.980,1.960,12.760,14.830
59,263,Torrey Pines Blacks Beach,32.890,-117.254,295,3.160,334.280,2.020,12.890,14.990
60,265,Trestles,33.385,-117.594,291,1.940,341.230,1.860,9.150,14.910
61,268,Venice Beach,33.985,-118.470,58,1.770,18.860,1.960,10.980,14.380
62,277,Zuma Beach County Park,34.022,-118.831,853,3.400,24.800,1.790,10.580,14.420

In [73]:
json_data3

{'hours': [{'airTemperature': {'noaa': 10.88, 'sg': 10.88},
   'time': '2023-01-20T06:00:00+00:00',
   'waterTemperature': {'meto': 14.42, 'noaa': 13.71, 'sg': 14.42},
   'waveHeight': {'icon': 1.83, 'noaa': 0.8, 'sg': 1.83},
   'windDirection': {'icon': 37.6, 'noaa': 49.77, 'sg': 37.6},
   'windSpeed': {'icon': 3.25, 'noaa': 5.9, 'sg': 3.25}},
  {'airTemperature': {'noaa': 10.58, 'sg': 10.58},
   'time': '2023-01-20T07:00:00+00:00',
   'waterTemperature': {'meto': 14.42, 'noaa': 13.65, 'sg': 14.42},
   'waveHeight': {'icon': 1.79, 'noaa': 0.74, 'sg': 1.79},
   'windDirection': {'icon': 24.8, 'noaa': 44.03, 'sg': 24.8},
   'windSpeed': {'icon': 3.4, 'noaa': 5.37, 'sg': 3.4}},
  {'airTemperature': {'noaa': 10.29, 'sg': 10.29},
   'time': '2023-01-20T08:00:00+00:00',
   'waterTemperature': {'meto': 14.41, 'noaa': 13.58, 'sg': 14.41},
   'waveHeight': {'icon': 1.76, 'noaa': 0.68, 'sg': 1.76},
   'windDirection': {'icon': 11.99, 'noaa': 38.29, 'sg': 11.99},
   'windSpeed': {'icon': 3.54, 'noaa': 4.84, 'sg': 3.54}},
  {'airTemperature': {'noaa': 9.99, 'sg': 9.99},
   'time': '2023-01-20T09:00:00+00:00',
   'waterTemperature': {'meto': 14.41, 'noaa': 13.52, 'sg': 14.41},
   'waveHeight': {'icon': 1.72, 'noaa': 0.62, 'sg': 1.72},
   'windDirection': {'icon': 359.19, 'noaa': 32.55, 'sg': 359.19},
   'windSpeed': {'icon': 3.69, 'noaa': 4.31, 'sg': 3.69}},
  {'airTemperature': {'noaa': 9.86, 'sg': 9.86},
   'time': '2023-01-20T10:00:00+00:00',
   'waterTemperature': {'meto': 14.4, 'noaa': 13.54, 'sg': 14.4},
   'waveHeight': {'icon': 1.67, 'noaa': 0.55, 'sg': 1.67},
   'windDirection': {'icon': 359.39, 'noaa': 28.51, 'sg': 359.39},
   'windSpeed': {'icon': 3.59, 'noaa': 4.36, 'sg': 3.59}},
  {'airTemperature': {'noaa': 9.73, 'sg': 9.73},
   'time': '2023-01-20T11:00:00+00:00',
   'waterTemperature': {'meto': 14.4, 'noaa': 13.55, 'sg': 14.4},
   'waveHeight': {'icon': 1.63, 'noaa': 0.49, 'sg': 1.63},
   'windDirection': {'icon': 359.58, 'noaa': 24.48, 'sg': 359.58},
   'windSpeed': {'icon': 3.5, 'noaa': 4.4, 'sg': 3.5}},
  {'airTemperature': {'noaa': 9.6, 'sg': 9.6},
   'time': '2023-01-20T12:00:00+00:00',
   'waterTemperature': {'meto': 14.4, 'noaa': 13.56, 'sg': 14.4},
   'waveHeight': {'icon': 1.58, 'noaa': 0.42, 'sg': 1.58},
   'windDirection': {'icon': 359.78, 'noaa': 20.44, 'sg': 359.78},
   'windSpeed': {'icon': 3.4, 'noaa': 4.45, 'sg': 3.4}},
  {'airTemperature': {'noaa': 9.53, 'sg': 9.53},
   'time': '2023-01-20T13:00:00+00:00',
   'waterTemperature': {'meto': 14.4, 'noaa': 13.54, 'sg': 14.4},
   'waveHeight': {'icon': 1.54, 'noaa': 0.4, 'sg': 1.54},
   'windDirection': {'icon': 3.5, 'noaa': 18.95, 'sg': 3.5},
   'windSpeed': {'icon': 3.44, 'noaa': 4.31, 'sg': 3.44}},
  {'airTemperature': {'noaa': 9.47, 'sg': 9.47},
   'time': '2023-01-20T14:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.53, 'sg': 14.39},
   'waveHeight': {'icon': 1.51, 'noaa': 0.38, 'sg': 1.51},
   'windDirection': {'icon': 7.21, 'noaa': 17.47, 'sg': 7.21},
   'windSpeed': {'icon': 3.49, 'noaa': 4.17, 'sg': 3.49}},
  {'airTemperature': {'noaa': 9.4, 'sg': 9.4},
   'time': '2023-01-20T15:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.51, 'sg': 14.39},
   'waveHeight': {'icon': 1.47, 'noaa': 0.36, 'sg': 1.47},
   'windDirection': {'icon': 10.93, 'noaa': 15.98, 'sg': 10.93},
   'windSpeed': {'icon': 3.53, 'noaa': 4.03, 'sg': 3.53}},
  {'airTemperature': {'noaa': 10.31, 'sg': 10.31},
   'time': '2023-01-20T16:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.54, 'sg': 14.39},
   'waveHeight': {'icon': 1.45, 'noaa': 0.35, 'sg': 1.45},
   'windDirection': {'icon': 28.72, 'noaa': 38.41, 'sg': 28.72},
   'windSpeed': {'icon': 3.1, 'noaa': 3.15, 'sg': 3.1}},
  {'airTemperature': {'noaa': 11.23, 'sg': 11.23},
   'time': '2023-01-20T17:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.58, 'sg': 14.39},
   'waveHeight': {'icon': 1.42, 'noaa': 0.33, 'sg': 1.42},
   'windDirection': {'icon': 46.5, 'noaa': 60.83, 'sg': 46.5},
   'windSpeed': {'icon': 2.66, 'noaa': 2.28, 'sg': 2.66}},
  {'airTemperature': {'noaa': 12.14, 'sg': 12.14},
   'time': '2023-01-20T18:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.61, 'sg': 14.39},
   'waveHeight': {'icon': 1.4, 'noaa': 0.32, 'sg': 1.4},
   'windDirection': {'icon': 64.29, 'noaa': 83.26, 'sg': 64.29},
   'windSpeed': {'icon': 2.23, 'noaa': 1.4, 'sg': 2.23}},
  {'airTemperature': {'noaa': 12.28, 'sg': 12.28},
   'time': '2023-01-20T19:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.74, 'sg': 14.39},
   'waveHeight': {'icon': 1.38, 'noaa': 0.31, 'sg': 1.38},
   'windDirection': {'icon': 102.4, 'noaa': 123.34, 'sg': 102.4},
   'windSpeed': {'icon': 2.08, 'noaa': 1.66, 'sg': 2.08}},
  {'airTemperature': {'noaa': 12.41, 'sg': 12.41},
   'time': '2023-01-20T20:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.87, 'sg': 14.39},
   'waveHeight': {'icon': 1.37, 'noaa': 0.3, 'sg': 1.37},
   'windDirection': {'icon': 140.5, 'noaa': 163.43, 'sg': 140.5},
   'windSpeed': {'icon': 1.92, 'noaa': 1.92, 'sg': 1.92}},
  {'airTemperature': {'noaa': 12.54, 'sg': 12.54},
   'time': '2023-01-20T21:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 14.0, 'sg': 14.39},
   'waveHeight': {'icon': 1.35, 'noaa': 0.29, 'sg': 1.35},
   'windDirection': {'icon': 178.61, 'noaa': 203.51, 'sg': 178.61},
   'windSpeed': {'icon': 1.77, 'noaa': 2.18, 'sg': 1.77}},
  {'airTemperature': {'noaa': 12.76, 'sg': 12.76},
   'time': '2023-01-20T22:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.88, 'sg': 14.39},
   'waveHeight': {'icon': 1.34, 'noaa': 0.29, 'sg': 1.34},
   'windDirection': {'icon': 203.24, 'noaa': 221.37, 'sg': 203.24},
   'windSpeed': {'icon': 1.99, 'noaa': 2.77, 'sg': 1.99}},
  {'airTemperature': {'noaa': 12.97, 'sg': 12.97},
   'time': '2023-01-20T23:00:00+00:00',
   'waterTemperature': {'meto': 14.39, 'noaa': 13.75, 'sg': 14.39},
   'waveHeight': {'icon': 1.32, 'noaa': 0.3, 'sg': 1.32},
   'windDirection': {'icon': 227.87, 'noaa': 239.22, 'sg': 227.87},
   'windSpeed': {'icon': 2.2, 'noaa': 3.36, 'sg': 2.2}},
  {'airTemperature': {'noaa': 13.19, 'sg': 13.19},
   'time': '2023-01-21T00:00:00+00:00',
   'waterTemperature': {'meto': 14.53, 'noaa': 13.63, 'sg': 14.53},
   'waveHeight': {'icon': 1.31, 'noaa': 0.3, 'sg': 1.31},
   'windDirection': {'icon': 252.5, 'noaa': 257.08, 'sg': 252.5},
   'windSpeed': {'icon': 2.42, 'noaa': 3.95, 'sg': 2.42}},
  {'airTemperature': {'noaa': 12.89, 'sg': 12.89},
   'time': '2023-01-21T01:00:00+00:00',
   'waterTemperature': {'meto': 14.48, 'noaa': 13.64, 'sg': 14.48},
   'waveHeight': {'icon': 1.3, 'noaa': 0.31, 'sg': 1.3},
   'windDirection': {'icon': 278.93, 'noaa': 277.9, 'sg': 278.93},
   'windSpeed': {'icon': 2.47, 'noaa': 4.0, 'sg': 2.47}},
  {'airTemperature': {'noaa': 12.6, 'sg': 12.6},
   'time': '2023-01-21T02:00:00+00:00',
   'waterTemperature': {'meto': 14.46, 'noaa': 13.65, 'sg': 14.46},
   'waveHeight': {'icon': 1.28, 'noaa': 0.31, 'sg': 1.28},
   'windDirection': {'icon': 305.36, 'noaa': 298.73, 'sg': 305.36},
   'windSpeed': {'icon': 2.51, 'noaa': 4.05, 'sg': 2.51}},
  {'airTemperature': {'noaa': 12.31, 'sg': 12.31},
   'time': '2023-01-21T03:00:00+00:00',
   'waterTemperature': {'meto': 14.44, 'noaa': 13.65, 'sg': 14.44},
   'waveHeight': {'icon': 1.27, 'noaa': 0.32, 'sg': 1.27},
   'windDirection': {'icon': 331.79, 'noaa': 319.55, 'sg': 331.79},
   'windSpeed': {'icon': 2.56, 'noaa': 4.1, 'sg': 2.56}},
  {'airTemperature': {'noaa': 12.04, 'sg': 12.04},
   'time': '2023-01-21T04:00:00+00:00',
   'waterTemperature': {'meto': 14.42, 'noaa': 13.61, 'sg': 14.42},
   'waveHeight': {'icon': 1.26, 'noaa': 0.31, 'sg': 1.26},
   'windDirection': {'icon': 346.51, 'noaa': 336.13, 'sg': 346.51},
   'windSpeed': {'icon': 2.79, 'noaa': 3.71, 'sg': 2.79}},
  {'airTemperature': {'noaa': 11.76, 'sg': 11.76},
   'time': '2023-01-21T05:00:00+00:00',
   'waterTemperature': {'meto': 14.41, 'noaa': 13.57, 'sg': 14.41},
   'waveHeight': {'icon': 1.24, 'noaa': 0.3, 'sg': 1.24},
   'windDirection': {'icon': 1.23, 'noaa': 352.72, 'sg': 1.23},
   'windSpeed': {'icon': 3.03, 'noaa': 3.31, 'sg': 3.03}}],
 'meta': {'cost': 1,
  'dailyQuota': 1000,
  'end': '2023-01-21 05:59',
  'lat': 34.022,
  'lng': -118.831,
  'params': ['waveHeight',
   'airTemperature',
   'windSpeed',
   'windDirection',
   'waterTemperature'],
  'requestCount': 258,
  'start': '2023-01-20 06:00'}}

In [19]:
start = arrow.get('2023-01-10')

response = requests.get(
  'https://api.stormglass.io/v2/tide/extremes/point',
  params={
    'lat': 33.6595,
    'lng': -117.9988,
    'start': start.to('UTC').timestamp(),  # Convert to UTC timestamp
    'end': start.shift(days=5).to('UTC').timestamp(),
  },
  headers={
    'Authorization': 'd87dfa70-985c-11ed-b59d-0242ac130002-d87dfade-985c-11ed-b59d-0242ac130002'
  }
)

# Do something with response data.
json_data2 = response.json()

In [20]:
print(json_data2)

{'data': [{'height': -0.9910802010073636, 'time': '2023-01-10T01:04:00+00:00', 'type': 'low'}, {'height': 0.2536876195880605, 'time': '2023-01-10T07:50:00+00:00', 'type': 'high'}, {'height': -0.08006869038119947, 'time': '2023-01-10T12:09:00+00:00', 'type': 'low'}, {'height': 0.7791868246210575, 'time': '2023-01-10T18:15:00+00:00', 'type': 'high'}, {'height': -0.9094307174745868, 'time': '2023-01-11T01:34:00+00:00', 'type': 'low'}, {'height': 0.2701997232161289, 'time': '2023-01-11T08:25:00+00:00', 'type': 'high'}, {'height': -0.0595229304571316, 'time': '2023-01-11T12:53:00+00:00', 'type': 'low'}, {'height': 0.6438937592972109, 'time': '2023-01-11T18:50:00+00:00', 'type': 'high'}, {'height': -0.8082580659425457, 'time': '2023-01-12T02:04:00+00:00', 'type': 'low'}, {'height': 0.30362188625867526, 'time': '2023-01-12T09:03:00+00:00', 'type': 'high'}, {'height': -0.044200165305219266, 'time': '2023-01-12T13:50:00+00:00', 'type': 'low'}, {'height': 0.47463861994604356, 'time': '2023-01-12T19:29:00+00:00', 'type': 'high'}, {'height': -0.6898984077844669, 'time': '2023-01-13T02:35:00+00:00', 'type': 'low'}, {'height': 0.35773119348028126, 'time': '2023-01-13T09:43:00+00:00', 'type': 'high'}, {'height': -0.05924373954447144, 'time': '2023-01-13T15:09:00+00:00', 'type': 'low'}, {'height': 0.28024872376063126, 'time': '2023-01-13T20:20:00+00:00', 'type': 'high'}, {'height': -0.5592881196604452, 'time': '2023-01-14T03:07:00+00:00', 'type': 'low'}, {'height': 0.4350377177484438, 'time': '2023-01-14T10:26:00+00:00', 'type': 'high'}, {'height': -0.1486120427821022, 'time': '2023-01-14T16:53:00+00:00', 'type': 'low'}, {'height': 0.08765484718009911, 'time': '2023-01-14T21:41:00+00:00', 'type': 'high'}], 'meta': {'cost': 1, 'dailyQuota': 10, 'datum': 'MSL', 'end': '2023-01-15 00:00', 'lat': 33.6595, 'lng': -117.9988, 'requestCount': 4, 'start': '2023-01-10 00:00', 'station': {'distance': 12, 'lat': 33.6033, 'lng': -117.883, 'name': 'newport beach, newport bay entrance, ca', 'source': 'noaa'}}}

In [31]:
import json
print(json.dumps(json_data2, sort_keys=True, indent=3))

{
   "data": [
      {
         "height": -0.9910802010073636,
         "time": "2023-01-10T01:04:00+00:00",
         "type": "low"
      },
      {
         "height": 0.2536876195880605,
         "time": "2023-01-10T07:50:00+00:00",
         "type": "high"
      },
      {
         "height": -0.08006869038119947,
         "time": "2023-01-10T12:09:00+00:00",
         "type": "low"
      },
      {
         "height": 0.7791868246210575,
         "time": "2023-01-10T18:15:00+00:00",
         "type": "high"
      },
      {
         "height": -0.9094307174745868,
         "time": "2023-01-11T01:34:00+00:00",
         "type": "low"
      },
      {
         "height": 0.2701997232161289,
         "time": "2023-01-11T08:25:00+00:00",
         "type": "high"
      },
      {
         "height": -0.0595229304571316,
         "time": "2023-01-11T12:53:00+00:00",
         "type": "low"
      },
      {
         "height": 0.6438937592972109,
         "time": "2023-01-11T18:50:00+00:00",
         "type": "high"
      },
      {
         "height": -0.8082580659425457,
         "time": "2023-01-12T02:04:00+00:00",
         "type": "low"
      },
      {
         "height": 0.30362188625867526,
         "time": "2023-01-12T09:03:00+00:00",
         "type": "high"
      },
      {
         "height": -0.044200165305219266,
         "time": "2023-01-12T13:50:00+00:00",
         "type": "low"
      },
      {
         "height": 0.47463861994604356,
         "time": "2023-01-12T19:29:00+00:00",
         "type": "high"
      },
      {
         "height": -0.6898984077844669,
         "time": "2023-01-13T02:35:00+00:00",
         "type": "low"
      },
      {
         "height": 0.35773119348028126,
         "time": "2023-01-13T09:43:00+00:00",
         "type": "high"
      },
      {
         "height": -0.05924373954447144,
         "time": "2023-01-13T15:09:00+00:00",
         "type": "low"
      },
      {
         "height": 0.28024872376063126,
         "time": "2023-01-13T20:20:00+00:00",
         "type": "high"
      },
      {
         "height": -0.5592881196604452,
         "time": "2023-01-14T03:07:00+00:00",
         "type": "low"
      },
      {
         "height": 0.4350377177484438,
         "time": "2023-01-14T10:26:00+00:00",
         "type": "high"
      },
      {
         "height": -0.1486120427821022,
         "time": "2023-01-14T16:53:00+00:00",
         "type": "low"
      },
      {
         "height": 0.08765484718009911,
         "time": "2023-01-14T21:41:00+00:00",
         "type": "high"
      }
   ],
   "meta": {
      "cost": 1,
      "dailyQuota": 10,
      "datum": "MSL",
      "end": "2023-01-15 00:00",
      "lat": 33.6595,
      "lng": -117.9988,
      "requestCount": 4,
      "start": "2023-01-10 00:00",
      "station": {
         "distance": 12,
         "lat": 33.6033,
         "lng": -117.883,
         "name": "newport beach, newport bay entrance, ca",
         "source": "noaa"
      }
   }
}

In [30]:
import json

print(json.dumps(json_data, sort_keys=True, indent=4))

{
    "hours": [
        {
            "airTemperature": {
                "noaa": 12.84,
                "sg": 12.84
            },
            "time": "2023-01-20T06:00:00+00:00",
            "waveHeight": {
                "icon": 1.86,
                "meteo": 1.29,
                "noaa": 0.83,
                "sg": 1.29
            }
        },
        {
            "airTemperature": {
                "noaa": 12.76,
                "sg": 12.76
            },
            "time": "2023-01-20T07:00:00+00:00",
            "waveHeight": {
                "icon": 1.88,
                "meteo": 1.3,
                "noaa": 0.82,
                "sg": 1.3
            }
        },
        {
            "airTemperature": {
                "noaa": 12.68,
                "sg": 12.68
            },
            "time": "2023-01-20T08:00:00+00:00",
            "waveHeight": {
                "icon": 1.89,
                "meteo": 1.3,
                "noaa": 0.82,
                "sg": 1.3
            }
        },
        {
            "airTemperature": {
                "noaa": 12.6,
                "sg": 12.6
            },
            "time": "2023-01-20T09:00:00+00:00",
            "waveHeight": {
                "icon": 1.91,
                "meteo": 1.31,
                "noaa": 0.81,
                "sg": 1.31
            }
        },
        {
            "airTemperature": {
                "noaa": 12.6,
                "sg": 12.6
            },
            "time": "2023-01-20T10:00:00+00:00",
            "waveHeight": {
                "icon": 1.89,
                "meteo": 1.29,
                "noaa": 0.78,
                "sg": 1.29
            }
        },
        {
            "airTemperature": {
                "noaa": 12.59,
                "sg": 12.59
            },
            "time": "2023-01-20T11:00:00+00:00",
            "waveHeight": {
                "icon": 1.87,
                "meteo": 1.26,
                "noaa": 0.75,
                "sg": 1.26
            }
        },
        {
            "airTemperature": {
                "noaa": 12.59,
                "sg": 12.59
            },
            "time": "2023-01-20T12:00:00+00:00",
            "waveHeight": {
                "icon": 1.85,
                "meteo": 1.24,
                "noaa": 0.72,
                "sg": 1.24
            }
        },
        {
            "airTemperature": {
                "noaa": 12.46,
                "sg": 12.46
            },
            "time": "2023-01-20T13:00:00+00:00",
            "waveHeight": {
                "icon": 1.82,
                "meteo": 1.2,
                "noaa": 0.69,
                "sg": 1.2
            }
        },
        {
            "airTemperature": {
                "noaa": 12.33,
                "sg": 12.33
            },
            "time": "2023-01-20T14:00:00+00:00",
            "waveHeight": {
                "icon": 1.78,
                "meteo": 1.17,
                "noaa": 0.66,
                "sg": 1.17
            }
        },
        {
            "airTemperature": {
                "noaa": 12.2,
                "sg": 12.2
            },
            "time": "2023-01-20T15:00:00+00:00",
            "waveHeight": {
                "icon": 1.75,
                "meteo": 1.13,
                "noaa": 0.63,
                "sg": 1.13
            }
        },
        {
            "airTemperature": {
                "noaa": 12.38,
                "sg": 12.38
            },
            "time": "2023-01-20T16:00:00+00:00",
            "waveHeight": {
                "icon": 1.71,
                "meteo": 1.1,
                "noaa": 0.59,
                "sg": 1.1
            }
        },
        {
            "airTemperature": {
                "noaa": 12.56,
                "sg": 12.56
            },
            "time": "2023-01-20T17:00:00+00:00",
            "waveHeight": {
                "icon": 1.68,
                "meteo": 1.06,
                "noaa": 0.54,
                "sg": 1.06
            }
        },
        {
            "airTemperature": {
                "noaa": 12.74,
                "sg": 12.74
            },
            "time": "2023-01-20T18:00:00+00:00",
            "waveHeight": {
                "icon": 1.64,
                "meteo": 1.03,
                "noaa": 0.5,
                "sg": 1.03
            }
        },
        {
            "airTemperature": {
                "noaa": 13.08,
                "sg": 13.08
            },
            "time": "2023-01-20T19:00:00+00:00",
            "waveHeight": {
                "icon": 1.61,
                "meteo": 1.01,
                "noaa": 0.48,
                "sg": 1.01
            }
        },
        {
            "airTemperature": {
                "noaa": 13.41,
                "sg": 13.41
            },
            "time": "2023-01-20T20:00:00+00:00",
            "waveHeight": {
                "icon": 1.59,
                "meteo": 0.98,
                "noaa": 0.47,
                "sg": 0.98
            }
        },
        {
            "airTemperature": {
                "noaa": 13.74,
                "sg": 13.74
            },
            "time": "2023-01-20T21:00:00+00:00",
            "waveHeight": {
                "icon": 1.56,
                "meteo": 0.96,
                "noaa": 0.45,
                "sg": 0.96
            }
        },
        {
            "airTemperature": {
                "noaa": 13.66,
                "sg": 13.66
            },
            "time": "2023-01-20T22:00:00+00:00",
            "waveHeight": {
                "icon": 1.54,
                "meteo": 0.95,
                "noaa": 0.46,
                "sg": 0.95
            }
        },
        {
            "airTemperature": {
                "noaa": 13.59,
                "sg": 13.59
            },
            "time": "2023-01-20T23:00:00+00:00",
            "waveHeight": {
                "icon": 1.52,
                "meteo": 0.93,
                "noaa": 0.46,
                "sg": 0.93
            }
        },
        {
            "airTemperature": {
                "noaa": 13.51,
                "sg": 13.51
            },
            "time": "2023-01-21T00:00:00+00:00",
            "waveHeight": {
                "icon": 1.5,
                "meteo": 0.92,
                "noaa": 0.47,
                "sg": 0.92
            }
        },
        {
            "airTemperature": {
                "noaa": 13.53,
                "sg": 13.53
            },
            "time": "2023-01-21T01:00:00+00:00",
            "waveHeight": {
                "icon": 1.48,
                "meteo": 0.91,
                "noaa": 0.46,
                "sg": 0.91
            }
        },
        {
            "airTemperature": {
                "noaa": 13.56,
                "sg": 13.56
            },
            "time": "2023-01-21T02:00:00+00:00",
            "waveHeight": {
                "icon": 1.47,
                "meteo": 0.9,
                "noaa": 0.44,
                "sg": 0.9
            }
        },
        {
            "airTemperature": {
                "noaa": 13.58,
                "sg": 13.58
            },
            "time": "2023-01-21T03:00:00+00:00",
            "waveHeight": {
                "icon": 1.45,
                "meteo": 0.89,
                "noaa": 0.43,
                "sg": 0.89
            }
        },
        {
            "airTemperature": {
                "noaa": 13.57,
                "sg": 13.57
            },
            "time": "2023-01-21T04:00:00+00:00",
            "waveHeight": {
                "icon": 1.44,
                "meteo": 0.87,
                "noaa": 0.43,
                "sg": 0.87
            }
        },
        {
            "airTemperature": {
                "noaa": 13.56,
                "sg": 13.56
            },
            "time": "2023-01-21T05:00:00+00:00",
            "waveHeight": {
                "icon": 1.42,
                "meteo": 0.86,
                "noaa": 0.42,
                "sg": 0.86
            }
        }
    ],
    "meta": {
        "cost": 1,
        "dailyQuota": 10,
        "end": "2023-01-21 05:59",
        "lat": 33.6595,
        "lng": -117.9988,
        "params": [
            "waveHeight",
            "airTemperature"
        ],
        "requestCount": 2,
        "start": "2023-01-20 06:00"
    }
}

In [55]:
print(json_data)

{'hours': [{'airTemperature': {'noaa': 13.56, 'sg': 13.56}, 'time': '2023-01-20T06:00:00+00:00', 'waveHeight': {'icon': 1.99, 'meteo': 1.29, 'noaa': 1.06, 'sg': 1.29}}, {'airTemperature': {'noaa': 13.46, 'sg': 13.46}, 'time': '2023-01-20T07:00:00+00:00', 'waveHeight': {'icon': 1.96, 'meteo': 1.3, 'noaa': 1.06, 'sg': 1.3}}, {'airTemperature': {'noaa': 13.37, 'sg': 13.37}, 'time': '2023-01-20T08:00:00+00:00', 'waveHeight': {'icon': 1.94, 'meteo': 1.3, 'noaa': 1.07, 'sg': 1.3}}, {'airTemperature': {'noaa': 13.27, 'sg': 13.27}, 'time': '2023-01-20T09:00:00+00:00', 'waveHeight': {'icon': 1.91, 'meteo': 1.31, 'noaa': 1.07, 'sg': 1.31}}, {'airTemperature': {'noaa': 13.14, 'sg': 13.14}, 'time': '2023-01-20T10:00:00+00:00', 'waveHeight': {'icon': 1.86, 'meteo': 1.29, 'noaa': 1.0, 'sg': 1.29}}, {'airTemperature': {'noaa': 13.0, 'sg': 13.0}, 'time': '2023-01-20T11:00:00+00:00', 'waveHeight': {'icon': 1.81, 'meteo': 1.26, 'noaa': 0.94, 'sg': 1.26}}, {'airTemperature': {'noaa': 12.86, 'sg': 12.86}, 'time': '2023-01-20T12:00:00+00:00', 'waveHeight': {'icon': 1.76, 'meteo': 1.24, 'noaa': 0.87, 'sg': 1.24}}, {'airTemperature': {'noaa': 12.81, 'sg': 12.81}, 'time': '2023-01-20T13:00:00+00:00', 'waveHeight': {'icon': 1.72, 'meteo': 1.2, 'noaa': 0.83, 'sg': 1.2}}, {'airTemperature': {'noaa': 12.75, 'sg': 12.75}, 'time': '2023-01-20T14:00:00+00:00', 'waveHeight': {'icon': 1.67, 'meteo': 1.17, 'noaa': 0.78, 'sg': 1.17}}, {'airTemperature': {'noaa': 12.7, 'sg': 12.7}, 'time': '2023-01-20T15:00:00+00:00', 'waveHeight': {'icon': 1.63, 'meteo': 1.13, 'noaa': 0.74, 'sg': 1.13}}, {'airTemperature': {'noaa': 12.68, 'sg': 12.68}, 'time': '2023-01-20T16:00:00+00:00', 'waveHeight': {'icon': 1.6, 'meteo': 1.1, 'noaa': 0.7, 'sg': 1.1}}, {'airTemperature': {'noaa': 12.66, 'sg': 12.66}, 'time': '2023-01-20T17:00:00+00:00', 'waveHeight': {'icon': 1.57, 'meteo': 1.06, 'noaa': 0.65, 'sg': 1.06}}, {'airTemperature': {'noaa': 12.64, 'sg': 12.64}, 'time': '2023-01-20T18:00:00+00:00', 'waveHeight': {'icon': 1.54, 'meteo': 1.03, 'noaa': 0.61, 'sg': 1.03}}, {'airTemperature': {'noaa': 12.61, 'sg': 12.61}, 'time': '2023-01-20T19:00:00+00:00', 'waveHeight': {'icon': 1.52, 'meteo': 1.01, 'noaa': 0.59, 'sg': 1.01}}, {'airTemperature': {'noaa': 12.58, 'sg': 12.58}, 'time': '2023-01-20T20:00:00+00:00', 'waveHeight': {'icon': 1.5, 'meteo': 0.98, 'noaa': 0.57, 'sg': 0.98}}, {'airTemperature': {'noaa': 12.54, 'sg': 12.54}, 'time': '2023-01-20T21:00:00+00:00', 'waveHeight': {'icon': 1.48, 'meteo': 0.96, 'noaa': 0.55, 'sg': 0.96}}, {'airTemperature': {'noaa': 12.69, 'sg': 12.69}, 'time': '2023-01-20T22:00:00+00:00', 'waveHeight': {'icon': 1.46, 'meteo': 0.95, 'noaa': 0.54, 'sg': 0.95}}, {'airTemperature': {'noaa': 12.83, 'sg': 12.83}, 'time': '2023-01-20T23:00:00+00:00', 'waveHeight': {'icon': 1.45, 'meteo': 0.93, 'noaa': 0.54, 'sg': 0.93}}, {'airTemperature': {'noaa': 12.98, 'sg': 12.98}, 'time': '2023-01-21T00:00:00+00:00', 'waveHeight': {'icon': 1.43, 'meteo': 0.92, 'noaa': 0.53, 'sg': 0.92}}, {'airTemperature': {'noaa': 13.06, 'sg': 13.06}, 'time': '2023-01-21T01:00:00+00:00', 'waveHeight': {'icon': 1.42, 'meteo': 0.91, 'noaa': 0.52, 'sg': 0.91}}, {'airTemperature': {'noaa': 13.15, 'sg': 13.15}, 'time': '2023-01-21T02:00:00+00:00', 'waveHeight': {'icon': 1.4, 'meteo': 0.9, 'noaa': 0.52, 'sg': 0.9}}, {'airTemperature': {'noaa': 13.24, 'sg': 13.24}, 'time': '2023-01-21T03:00:00+00:00', 'waveHeight': {'icon': 1.39, 'meteo': 0.89, 'noaa': 0.51, 'sg': 0.89}}, {'airTemperature': {'noaa': 13.34, 'sg': 13.34}, 'time': '2023-01-21T04:00:00+00:00', 'waveHeight': {'icon': 1.37, 'meteo': 0.87, 'noaa': 0.51, 'sg': 0.87}}, {'airTemperature': {'noaa': 13.43, 'sg': 13.43}, 'time': '2023-01-21T05:00:00+00:00', 'waveHeight': {'icon': 1.36, 'meteo': 0.86, 'noaa': 0.5, 'sg': 0.86}}], 'meta': {'cost': 1, 'dailyQuota': 1000, 'end': '2023-01-21 05:59', 'lat': 33.707, 'lng': -118.285, 'params': ['waveHeight', 'airTemperature'], 'requestCount': 6, 'start': '2023-01-20 06:00'}}