In [1]:
import pandas as pd
import requests
import arrow
import requests

In [2]:
csv_path = "Surf.csv"

In [3]:
surf = pd.read_csv(csv_path, encoding="utf-8")
surf.head()

        spot  longitude  latitude  spot_id
0     Thurso  58.598988 -3.509359       47
1    Fistral  50.416497 -5.099329        1
2     Easkey  54.292499 -8.952585     1501
3  Manorbier  51.642795 -4.803594      993
4  Carbedelo  41.677002 -8.829828      193

In [4]:
surf_cali = surf.loc[(surf['longitude']< 43) & (surf['longitude']>32)]

In [5]:
surf_cali_df = surf_cali.loc[(surf_cali['latitude']> -123) & (surf_cali['latitude']< -113)]
surf_cali_df.reset_index(drop=True)

                         spot  longitude    latitude  spot_id
0                       Ponto  33.088162 -117.314436     1149
1              Cabrillo Point  33.706658 -118.285149      284
2                   Haggertys  33.802507 -118.400664      282
3                 Skunk Point  33.982632 -119.983868     1251
4                       Secos  34.038334 -118.879119      278
..                        ...        ...         ...      ...
58                  The Wedge  33.592853 -117.881037      287
59  Torrey Pines Blacks Beach  32.889556 -117.253649      295
60                   Trestles  33.385308 -117.593936      291
61               Venice Beach  33.984676 -118.470325       58
62     Zuma Beach County Park  34.021802 -118.831190      853

[63 rows x 4 columns]

In [6]:
surfcali1 = surf_cali_df.round(3)

In [7]:
for x, y in zip(surfcali1['latitude'],surfcali1['longitude']):
    print(f'{x}, {y}')

-117.314, 33.088
-118.285, 33.707
-118.401, 33.803
-119.984, 33.983
-118.879, 34.038
-119.303, 34.273
-119.882, 34.409
-120.054, 34.461
-121.121, 35.582
-121.977, 36.596
-122.026, 36.952
-121.972, 36.955
-121.844, 36.288
-119.843, 34.406
-117.32, 33.103
-121.93, 36.552
-120.906, 35.449
-118.96, 34.051
-117.257, 32.796
-122.216, 37.025
-119.917, 34.432
-119.412, 34.338
-118.004, 33.655
-120.501, 34.511
-117.774, 33.535
-122.502, 37.599
-118.194, 33.77
-118.194, 33.77
-118.417, 33.772
-118.8, 34.008
-118.396, 33.885
-121.862, 36.932
-122.537, 37.831
-122.497, 37.496
-117.251, 32.771
-121.114, 35.576
-120.866, 35.392
-120.866, 35.392
-121.791, 36.815
-117.93, 33.619
-117.829, 33.58
-117.251, 32.756
-120.612, 35.099
-117.385, 33.195
-117.258, 32.796
-119.388, 34.319
-118.806, 34.001
-119.407, 34.336
-117.719, 33.477
-117.621, 33.419
-118.5, 34.013
-117.255, 32.864
-118.107, 33.738
-117.142, 32.635
-117.276, 32.996
-117.292, 33.035
-117.273, 32.85
-120.499, 34.508
-117.881, 33.593
-117.254, 32.89
-117.594, 33.385
-118.47, 33.985
-118.831, 34.022

In [9]:
# Get first hour of today
start = arrow.now().floor('day')

# Get last hour of today
end = arrow.now().ceil('day')

response = requests.get(
  'https://api.stormglass.io/v2/weather/point',
  params={
    'lat': 34.022,
    'lng': -118.831,
    'params': ','.join(['waveHeight', 'airTemperature']),
    'start': start.to('UTC').timestamp(),  # Convert to UTC timestamp
    'end': end.to('UTC').timestamp()  # Convert to UTC timestamp
  },
  headers={
    'Authorization': 'd87dfa70-985c-11ed-b59d-0242ac130002-d87dfade-985c-11ed-b59d-0242ac130002'
  }
)

# Do something with response data.
json_data = response.json()

In [20]:
windspeed = []
winddirection = []
waveheight = []
airtemp = []
watertemp = []
cloudcover = []
gust = []
precipitation = []
visibility = []
wavedirection = []

url = 'https://api.stormglass.io/v2/weather/point'
for x, y in zip(surfcali1['latitude'], surfcali1['longitude']):
    try:
        lat = (f'{y}')
        lng = (f'{x}')

        params ={
            'lat': lat,
            'lng': lng,
            'params': ','.join(['waveHeight', 'airTemperature', 'windSpeed', 'windDirection', 'waterTemperature','cloudCover','gust','precipitation','visibility','waveDirection']),
            'start': start.to('UTC').timestamp(),  # Convert to UTC timestamp
            'end': end.to('UTC').timestamp()  # Convert to UTC timestamp
        }
        headers ={
        'Authorization': 'd87dfa70-985c-11ed-b59d-0242ac130002-d87dfade-985c-11ed-b59d-0242ac130002'
        }

        response = requests.get(url, params=params, headers=headers)
        json_data3 = response.json()

        windspeed_data = json_data3['hours'][0]['windSpeed']['sg']
        winddirection_data = json_data3['hours'][0]['windDirection']['sg']
        waveheight_data = json_data3['hours'][0]['waveHeight']['sg']
        airtemp_data = json_data3['hours'][0]['airTemperature']['sg']
        watertemp_data = json_data3['hours'][0]['waterTemperature']['sg']
        cloudcover_data = json_data3['hours'][0]['cloudCover']['sg']
        gust_data = json_data3['hours'][0]['gust']['sg']
        precipitation_data = json_data3['hours'][0]['precipitation']['sg']
        visibility_data = json_data3['hours'][0]['visibility']['sg']
        wavedirection_data = json_data3['hours'][0]['waveDirection']['sg']

        windspeed.append(windspeed_data)
        winddirection.append(winddirection_data)
        waveheight.append(waveheight_data)
        airtemp.append(airtemp_data)
        watertemp.append(watertemp_data)
        cloudcover.append(cloudcover_data)
        gust.append(gust_data)
        precipitation.append(precipitation_data)
        visibility.append(visibility_data)
        wavedirection.append(wavedirection_data)

    except:
        print('failed')
        print(f'at {x},{y}')

In [ ]:
json_data3['hours'][1]['windDirection']['icon']

In [21]:
df = pd.DataFrame({"wind speed":windspeed,
                    "wind direction":winddirection,
                    "wave height":waveheight,
                    "air temp":airtemp,
                    "water temp":watertemp,
                    "cloud cover":cloudcover,
                    "gust":gust,
                    "precipitation": precipitation,
                    "visibility":visibility,
                    "wave direction":wavedirection

})

In [22]:
df

,wind speed,wind direction,wave height,air temp,water temp,cloud cover,gust,precipitation,visibility,wave direction
0,1.58,65.06,1.92,13.88,15.00,4.8,1.13,0.0,24.13,286.27
1,2.41,48.54,1.18,13.51,14.54,6.0,1.93,0.0,24.13,277.40
2,2.41,48.54,1.79,11.14,14.50,5.0,8.03,0.0,24.13,282.03
3,5.60,338.02,3.36,12.76,13.81,5.0,6.33,0.0,24.13,303.23
4,3.75,357.42,1.84,10.67,14.19,15.0,9.03,0.0,24.13,285.51
...,...,...,...,...,...,...,...,...,...,...
58,3.60,6.31,1.18,14.52,14.64,0.1,14.23,0.0,24.13,277.40
59,1.58,65.06,1.92,13.88,15.00,4.8,1.13,0.0,24.13,286.27
60,1.88,9.17,1.18,7.83,15.04,0.0,1.73,0.0,24.13,277.40
61,2.41,48.54,1.79,11.14,14.36,5.0,8.03,0.0,24.13,282.03
62,5.04,25.09,1.64,10.67,14.30,15.0,9.03,0.0,24.13,282.19

In [15]:
surfcali1.reset_index(inplace=True)
surfcali1

    index                       spot  longitude  latitude  spot_id
0      41                      Ponto     33.088  -117.314     1149
1      42             Cabrillo Point     33.707  -118.285      284
2      43                  Haggertys     33.803  -118.401      282
3      44                Skunk Point     33.983  -119.984     1251
4      45                      Secos     34.038  -118.879      278
..    ...                        ...        ...       ...      ...
58    258                  The Wedge     33.593  -117.881      287
59    263  Torrey Pines Blacks Beach     32.890  -117.254      295
60    265                   Trestles     33.385  -117.594      291
61    268               Venice Beach     33.985  -118.470       58
62    277     Zuma Beach County Park     34.022  -118.831      853

[63 rows x 5 columns]

In [23]:
combined = surfcali1.join(df, how='left')

In [24]:
combined

,index,spot,longitude,latitude,spot_id,wind speed,wind direction,wave height,air temp,water temp,cloud cover,gust,precipitation,visibility,wave direction
0,41,Ponto,33.088,-117.314,1149,1.58,65.06,1.92,13.88,15.00,4.8,1.13,0.0,24.13,286.27
1,42,Cabrillo Point,33.707,-118.285,284,2.41,48.54,1.18,13.51,14.54,6.0,1.93,0.0,24.13,277.40
2,43,Haggertys,33.803,-118.401,282,2.41,48.54,1.79,11.14,14.50,5.0,8.03,0.0,24.13,282.03
3,44,Skunk Point,33.983,-119.984,1251,5.60,338.02,3.36,12.76,13.81,5.0,6.33,0.0,24.13,303.23
4,45,Secos,34.038,-118.879,278,3.75,357.42,1.84,10.67,14.19,15.0,9.03,0.0,24.13,285.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,258,The Wedge,33.593,-117.881,287,3.60,6.31,1.18,14.52,14.64,0.1,14.23,0.0,24.13,277.40
59,263,Torrey Pines Blacks Beach,32.890,-117.254,295,1.58,65.06,1.92,13.88,15.00,4.8,1.13,0.0,24.13,286.27
60,265,Trestles,33.385,-117.594,291,1.88,9.17,1.18,7.83,15.04,0.0,1.73,0.0,24.13,277.40
61,268,Venice Beach,33.985,-118.470,58,2.41,48.54,1.79,11.14,14.36,5.0,8.03,0.0,24.13,282.03
62,277,Zuma Beach County Park,34.022,-118.831,853,5.04,25.09,1.64,10.67,14.30,15.0,9.03,0.0,24.13,282.19

In [26]:
from sqlalchemy import create_engine

In [29]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.5-cp36-cp36m-macosx_10_14_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.2 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2.2 MB 2.5 MB/s eta 0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.5

In [30]:
protocol = 'postgresql'
username = 'postgres'
password = 'postgres'
host = 'localhost'
port = 5432
database_name = 'surf_DB'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [31]:
engine.table_names()

/Users/tommysmacbook/opt/anaconda3/envs/pythondata1/lib/python3.6/site-packages/ipykernel_launcher.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  """Entry point for launching an IPython kernel.

['current_surf']

In [32]:
combined.to_sql(name='current_surf', con=engine, if_exists='replace', index=False)

In [33]:
pd.read_sql_query('select * from current_surf', con=engine).head()

,index,spot,longitude,latitude,spot_id,wind speed,wind direction,wave height,air temp,water temp,cloud cover,gust,precipitation,visibility,wave direction
0,41,Ponto,33.088,-117.314,1149,1.58,65.06,1.92,13.88,15.00,4.8,1.13,0.0,24.13,286.27
1,42,Cabrillo Point,33.707,-118.285,284,2.41,48.54,1.18,13.51,14.54,6.0,1.93,0.0,24.13,277.40
2,43,Haggertys,33.803,-118.401,282,2.41,48.54,1.79,11.14,14.50,5.0,8.03,0.0,24.13,282.03
3,44,Skunk Point,33.983,-119.984,1251,5.60,338.02,3.36,12.76,13.81,5.0,6.33,0.0,24.13,303.23
4,45,Secos,34.038,-118.879,278,3.75,357.42,1.84,10.67,14.19,15.0,9.03,0.0,24.13,285.51

In [25]:
combined.dtypes

index               int64
spot               object
longitude         float64
latitude          float64
spot_id             int64
wind speed        float64
wind direction    float64
wave height       float64
air temp          float64
water temp        float64
cloud cover       float64
gust              float64
precipitation     float64
visibility        float64
wave direction    float64
dtype: object

In [19]:
json_data3

{'hours': [{'airTemperature': {'noaa': 10.67, 'sg': 10.67},
   'time': '2023-01-23T06:00:00+00:00',
   'waterTemperature': {'meto': 14.3, 'noaa': 13.16, 'sg': 14.3},
   'waveHeight': {'icon': 1.64, 'noaa': 0.56, 'sg': 1.64},
   'windDirection': {'icon': 25.09, 'noaa': 8.68, 'sg': 25.09},
   'windSpeed': {'icon': 5.04, 'noaa': 5.1, 'sg': 5.04}},
  {'airTemperature': {'noaa': 11.06, 'sg': 11.06},
   'time': '2023-01-23T07:00:00+00:00',
   'waterTemperature': {'meto': 14.28, 'noaa': 13.17, 'sg': 14.28},
   'waveHeight': {'icon': 1.66, 'noaa': 0.52, 'sg': 1.66},
   'windDirection': {'icon': 28.16, 'noaa': 22.17, 'sg': 28.16},
   'windSpeed': {'icon': 6.01, 'noaa': 5.82, 'sg': 6.01}},
  {'airTemperature': {'noaa': 11.44, 'sg': 11.44},
   'time': '2023-01-23T08:00:00+00:00',
   'waterTemperature': {'meto': 14.27, 'noaa': 13.18, 'sg': 14.27},
   'waveHeight': {'icon': 1.68, 'noaa': 0.49, 'sg': 1.68},
   'windDirection': {'icon': 31.23, 'noaa': 35.66, 'sg': 31.23},
   'windSpeed': {'icon': 6.98, 'noaa': 6.55, 'sg': 6.98}},
  {'airTemperature': {'noaa': 11.83, 'sg': 11.83},
   'time': '2023-01-23T09:00:00+00:00',
   'waterTemperature': {'meto': 14.26, 'noaa': 13.19, 'sg': 14.26},
   'waveHeight': {'icon': 1.7, 'noaa': 0.45, 'sg': 1.7},
   'windDirection': {'icon': 34.3, 'noaa': 49.15, 'sg': 34.3},
   'windSpeed': {'icon': 7.95, 'noaa': 7.27, 'sg': 7.95}},
  {'airTemperature': {'noaa': 11.51, 'sg': 11.51},
   'time': '2023-01-23T10:00:00+00:00',
   'waterTemperature': {'meto': 14.25, 'noaa': 13.15, 'sg': 14.25},
   'waveHeight': {'icon': 1.69, 'noaa': 0.45, 'sg': 1.69},
   'windDirection': {'icon': 33.23, 'noaa': 47.34, 'sg': 33.23},
   'windSpeed': {'icon': 7.5, 'noaa': 6.55, 'sg': 7.5}},
  {'airTemperature': {'noaa': 11.19, 'sg': 11.19},
   'time': '2023-01-23T11:00:00+00:00',
   'waterTemperature': {'meto': 14.24, 'noaa': 13.11, 'sg': 14.24},
   'waveHeight': {'icon': 1.69, 'noaa': 0.44, 'sg': 1.69},
   'windDirection': {'icon': 32.16, 'noaa': 45.52, 'sg': 32.16},
   'windSpeed': {'icon': 7.05, 'noaa': 5.84, 'sg': 7.05}},
  {'airTemperature': {'noaa': 10.88, 'sg': 10.88},
   'time': '2023-01-23T12:00:00+00:00',
   'waterTemperature': {'meto': 14.24, 'noaa': 13.07, 'sg': 14.24},
   'waveHeight': {'icon': 1.68, 'noaa': 0.44, 'sg': 1.68},
   'windDirection': {'icon': 31.09, 'noaa': 43.71, 'sg': 31.09},
   'windSpeed': {'icon': 6.6, 'noaa': 5.12, 'sg': 6.6}},
  {'airTemperature': {'noaa': 10.72, 'sg': 10.72},
   'time': '2023-01-23T13:00:00+00:00',
   'waterTemperature': {'meto': 14.23, 'noaa': 13.1, 'sg': 14.23},
   'waveHeight': {'icon': 1.64, 'noaa': 0.43, 'sg': 1.64},
   'windDirection': {'icon': 25.15, 'noaa': 36.43, 'sg': 25.15},
   'windSpeed': {'icon': 6.47, 'noaa': 5.22, 'sg': 6.47}},
  {'airTemperature': {'noaa': 10.56, 'sg': 10.56},
   'time': '2023-01-23T14:00:00+00:00',
   'waterTemperature': {'meto': 14.23, 'noaa': 13.12, 'sg': 14.23},
   'waveHeight': {'icon': 1.6, 'noaa': 0.41, 'sg': 1.6},
   'windDirection': {'icon': 19.2, 'noaa': 29.14, 'sg': 19.2},
   'windSpeed': {'icon': 6.33, 'noaa': 5.33, 'sg': 6.33}},
  {'airTemperature': {'noaa': 10.4, 'sg': 10.4},
   'time': '2023-01-23T15:00:00+00:00',
   'waterTemperature': {'meto': 14.22, 'noaa': 13.15, 'sg': 14.22},
   'waveHeight': {'icon': 1.56, 'noaa': 0.4, 'sg': 1.56},
   'windDirection': {'icon': 13.26, 'noaa': 21.86, 'sg': 13.26},
   'windSpeed': {'icon': 6.2, 'noaa': 5.43, 'sg': 6.2}},
  {'airTemperature': {'noaa': 11.2, 'sg': 11.2},
   'time': '2023-01-23T16:00:00+00:00',
   'waterTemperature': {'meto': 14.22, 'noaa': 13.17, 'sg': 14.22},
   'waveHeight': {'icon': 1.52, 'noaa': 0.39, 'sg': 1.52},
   'windDirection': {'icon': 7.93, 'noaa': 11.28, 'sg': 7.93},
   'windSpeed': {'icon': 6.1, 'noaa': 5.07, 'sg': 6.1}},
  {'airTemperature': {'noaa': 12.0, 'sg': 12.0},
   'time': '2023-01-23T17:00:00+00:00',
   'waterTemperature': {'meto': 14.22, 'noaa': 13.19, 'sg': 14.22},
   'waveHeight': {'icon': 1.48, 'noaa': 0.37, 'sg': 1.48},
   'windDirection': {'icon': 2.59, 'noaa': 0.7, 'sg': 2.59},
   'windSpeed': {'icon': 6.0, 'noaa': 4.71, 'sg': 6.0}},
  {'airTemperature': {'noaa': 12.79, 'sg': 12.79},
   'time': '2023-01-23T18:00:00+00:00',
   'waterTemperature': {'meto': 14.22, 'noaa': 13.21, 'sg': 14.22},
   'waveHeight': {'icon': 1.44, 'noaa': 0.36, 'sg': 1.44},
   'windDirection': {'icon': 357.26, 'noaa': 350.12, 'sg': 357.26},
   'windSpeed': {'icon': 5.9, 'noaa': 4.35, 'sg': 5.9}},
  {'airTemperature': {'noaa': 13.43, 'sg': 13.43},
   'time': '2023-01-23T19:00:00+00:00',
   'waterTemperature': {'meto': 14.22, 'noaa': 13.29, 'sg': 14.22},
   'waveHeight': {'icon': 1.41, 'noaa': 0.36, 'sg': 1.41},
   'windDirection': {'icon': 0.16, 'noaa': 337.26, 'sg': 0.16},
   'windSpeed': {'icon': 6.11, 'noaa': 4.89, 'sg': 6.11}},
  {'airTemperature': {'noaa': 14.07, 'sg': 14.07},
   'time': '2023-01-23T20:00:00+00:00',
   'waterTemperature': {'meto': 14.21, 'noaa': 13.37, 'sg': 14.21},
   'waveHeight': {'icon': 1.39, 'noaa': 0.36, 'sg': 1.39},
   'windDirection': {'icon': 3.07, 'noaa': 324.39, 'sg': 3.07},
   'windSpeed': {'icon': 6.31, 'noaa': 5.43, 'sg': 6.31}},
  {'airTemperature': {'noaa': 14.7, 'sg': 14.7},
   'time': '2023-01-23T21:00:00+00:00',
   'waterTemperature': {'meto': 14.21, 'noaa': 13.44, 'sg': 14.21},
   'waveHeight': {'icon': 1.36, 'noaa': 0.36, 'sg': 1.36},
   'windDirection': {'icon': 5.97, 'noaa': 311.53, 'sg': 5.97},
   'windSpeed': {'icon': 6.52, 'noaa': 5.97, 'sg': 6.52}},
  {'airTemperature': {'noaa': 14.36, 'sg': 14.36},
   'time': '2023-01-23T22:00:00+00:00',
   'waterTemperature': {'meto': 14.21, 'noaa': 13.38, 'sg': 14.21},
   'waveHeight': {'icon': 1.32, 'noaa': 0.4, 'sg': 1.32},
   'windDirection': {'icon': 358.24, 'noaa': 308.82, 'sg': 358.24},
   'windSpeed': {'icon': 6.1, 'noaa': 5.97, 'sg': 6.1}},
  {'airTemperature': {'noaa': 14.01, 'sg': 14.01},
   'time': '2023-01-23T23:00:00+00:00',
   'waterTemperature': {'meto': 14.21, 'noaa': 13.32, 'sg': 14.21},
   'waveHeight': {'icon': 1.27, 'noaa': 0.45, 'sg': 1.27},
   'windDirection': {'icon': 350.51, 'noaa': 306.1, 'sg': 350.51},
   'windSpeed': {'icon': 5.67, 'noaa': 5.98, 'sg': 5.67}},
  {'airTemperature': {'noaa': 13.66, 'sg': 13.66},
   'time': '2023-01-24T00:00:00+00:00',
   'waterTemperature': {'meto': 14.23, 'noaa': 13.26, 'sg': 14.23},
   'waveHeight': {'icon': 1.23, 'noaa': 0.49, 'sg': 1.23},
   'windDirection': {'icon': 342.78, 'noaa': 303.39, 'sg': 342.78},
   'windSpeed': {'icon': 5.25, 'noaa': 5.98, 'sg': 5.25}},
  {'airTemperature': {'noaa': 13.22, 'sg': 13.22},
   'time': '2023-01-24T01:00:00+00:00',
   'waterTemperature': {'meto': 14.16, 'noaa': 13.27, 'sg': 14.16},
   'waveHeight': {'icon': 1.2, 'noaa': 0.46, 'sg': 1.2},
   'windDirection': {'icon': 337.54, 'noaa': 311.57, 'sg': 337.54},
   'windSpeed': {'icon': 5.09, 'noaa': 5.67, 'sg': 5.09}},
  {'airTemperature': {'noaa': 12.78, 'sg': 12.78},
   'time': '2023-01-24T02:00:00+00:00',
   'waterTemperature': {'meto': 14.09, 'noaa': 13.27, 'sg': 14.09},
   'waveHeight': {'icon': 1.16, 'noaa': 0.44, 'sg': 1.16},
   'windDirection': {'icon': 332.3, 'noaa': 319.76, 'sg': 332.3},
   'windSpeed': {'icon': 4.94, 'noaa': 5.37, 'sg': 4.94}},
  {'airTemperature': {'noaa': 12.34, 'sg': 12.34},
   'time': '2023-01-24T03:00:00+00:00',
   'waterTemperature': {'meto': 14.05, 'noaa': 13.28, 'sg': 14.05},
   'waveHeight': {'icon': 1.13, 'noaa': 0.41, 'sg': 1.13},
   'windDirection': {'icon': 327.06, 'noaa': 327.94, 'sg': 327.06},
   'windSpeed': {'icon': 4.78, 'noaa': 5.06, 'sg': 4.78}},
  {'airTemperature': {'noaa': 12.33, 'sg': 12.33},
   'time': '2023-01-24T04:00:00+00:00',
   'waterTemperature': {'meto': 14.03, 'noaa': 13.25, 'sg': 14.03},
   'waveHeight': {'icon': 1.12, 'noaa': 0.38, 'sg': 1.12},
   'windDirection': {'icon': 335.69, 'noaa': 339.89, 'sg': 335.69},
   'windSpeed': {'icon': 4.34, 'noaa': 4.67, 'sg': 4.34}},
  {'airTemperature': {'noaa': 12.31, 'sg': 12.31},
   'time': '2023-01-24T05:00:00+00:00',
   'waterTemperature': {'meto': 14.01, 'noaa': 13.22, 'sg': 14.01},
   'waveHeight': {'icon': 1.12, 'noaa': 0.35, 'sg': 1.12},
   'windDirection': {'icon': 344.33, 'noaa': 351.83, 'sg': 344.33},
   'windSpeed': {'icon': 3.91, 'noaa': 4.28, 'sg': 3.91}}],
 'meta': {'cost': 1,
  'dailyQuota': 1000,
  'end': '2023-01-24 05:59',
  'lat': 34.022,
  'lng': -118.831,
  'params': ['waveHeight',
   'airTemperature',
   'windSpeed',
   'windDirection',
   'waterTemperature'],
  'requestCount': 127,
  'start': '2023-01-23 06:00'}}

In [ ]:
start = arrow.get('2023-01-10')

response = requests.get(
  'https://api.stormglass.io/v2/tide/extremes/point',
  params={
    'lat': 33.6595,
    'lng': -117.9988,
    'start': start.to('UTC').timestamp(),  # Convert to UTC timestamp
    'end': start.shift(days=5).to('UTC').timestamp(),
  },
  headers={
    'Authorization': 'd87dfa70-985c-11ed-b59d-0242ac130002-d87dfade-985c-11ed-b59d-0242ac130002'
  }
)

# Do something with response data.
json_data2 = response.json()

In [ ]:
print(json_data2)

In [ ]:
import json
print(json.dumps(json_data2, sort_keys=True, indent=3))

In [11]:
import json

print(json.dumps(json_data, sort_keys=True, indent=4))

{
    "hours": [
        {
            "airTemperature": {
                "noaa": 10.67,
                "sg": 10.67
            },
            "time": "2023-01-23T06:00:00+00:00",
            "waveHeight": {
                "icon": 1.64,
                "noaa": 0.56,
                "sg": 1.64
            }
        },
        {
            "airTemperature": {
                "noaa": 11.06,
                "sg": 11.06
            },
            "time": "2023-01-23T07:00:00+00:00",
            "waveHeight": {
                "icon": 1.66,
                "noaa": 0.52,
                "sg": 1.66
            }
        },
        {
            "airTemperature": {
                "noaa": 11.44,
                "sg": 11.44
            },
            "time": "2023-01-23T08:00:00+00:00",
            "waveHeight": {
                "icon": 1.68,
                "noaa": 0.49,
                "sg": 1.68
            }
        },
        {
            "airTemperature": {
                "noaa": 11.83,
                "sg": 11.83
            },
            "time": "2023-01-23T09:00:00+00:00",
            "waveHeight": {
                "icon": 1.7,
                "noaa": 0.45,
                "sg": 1.7
            }
        },
        {
            "airTemperature": {
                "noaa": 11.51,
                "sg": 11.51
            },
            "time": "2023-01-23T10:00:00+00:00",
            "waveHeight": {
                "icon": 1.69,
                "noaa": 0.45,
                "sg": 1.69
            }
        },
        {
            "airTemperature": {
                "noaa": 11.19,
                "sg": 11.19
            },
            "time": "2023-01-23T11:00:00+00:00",
            "waveHeight": {
                "icon": 1.69,
                "noaa": 0.44,
                "sg": 1.69
            }
        },
        {
            "airTemperature": {
                "noaa": 10.88,
                "sg": 10.88
            },
            "time": "2023-01-23T12:00:00+00:00",
            "waveHeight": {
                "icon": 1.68,
                "noaa": 0.44,
                "sg": 1.68
            }
        },
        {
            "airTemperature": {
                "noaa": 10.72,
                "sg": 10.72
            },
            "time": "2023-01-23T13:00:00+00:00",
            "waveHeight": {
                "icon": 1.64,
                "noaa": 0.43,
                "sg": 1.64
            }
        },
        {
            "airTemperature": {
                "noaa": 10.56,
                "sg": 10.56
            },
            "time": "2023-01-23T14:00:00+00:00",
            "waveHeight": {
                "icon": 1.6,
                "noaa": 0.41,
                "sg": 1.6
            }
        },
        {
            "airTemperature": {
                "noaa": 10.4,
                "sg": 10.4
            },
            "time": "2023-01-23T15:00:00+00:00",
            "waveHeight": {
                "icon": 1.56,
                "noaa": 0.4,
                "sg": 1.56
            }
        },
        {
            "airTemperature": {
                "noaa": 11.2,
                "sg": 11.2
            },
            "time": "2023-01-23T16:00:00+00:00",
            "waveHeight": {
                "icon": 1.52,
                "noaa": 0.39,
                "sg": 1.52
            }
        },
        {
            "airTemperature": {
                "noaa": 12.0,
                "sg": 12.0
            },
            "time": "2023-01-23T17:00:00+00:00",
            "waveHeight": {
                "icon": 1.48,
                "noaa": 0.37,
                "sg": 1.48
            }
        },
        {
            "airTemperature": {
                "noaa": 12.79,
                "sg": 12.79
            },
            "time": "2023-01-23T18:00:00+00:00",
            "waveHeight": {
                "icon": 1.44,
                "noaa": 0.36,
                "sg": 1.44
            }
        },
        {
            "airTemperature": {
                "noaa": 13.43,
                "sg": 13.43
            },
            "time": "2023-01-23T19:00:00+00:00",
            "waveHeight": {
                "icon": 1.41,
                "noaa": 0.36,
                "sg": 1.41
            }
        },
        {
            "airTemperature": {
                "noaa": 14.07,
                "sg": 14.07
            },
            "time": "2023-01-23T20:00:00+00:00",
            "waveHeight": {
                "icon": 1.39,
                "noaa": 0.36,
                "sg": 1.39
            }
        },
        {
            "airTemperature": {
                "noaa": 14.7,
                "sg": 14.7
            },
            "time": "2023-01-23T21:00:00+00:00",
            "waveHeight": {
                "icon": 1.36,
                "noaa": 0.36,
                "sg": 1.36
            }
        },
        {
            "airTemperature": {
                "noaa": 14.36,
                "sg": 14.36
            },
            "time": "2023-01-23T22:00:00+00:00",
            "waveHeight": {
                "icon": 1.32,
                "noaa": 0.4,
                "sg": 1.32
            }
        },
        {
            "airTemperature": {
                "noaa": 14.01,
                "sg": 14.01
            },
            "time": "2023-01-23T23:00:00+00:00",
            "waveHeight": {
                "icon": 1.27,
                "noaa": 0.45,
                "sg": 1.27
            }
        },
        {
            "airTemperature": {
                "noaa": 13.66,
                "sg": 13.66
            },
            "time": "2023-01-24T00:00:00+00:00",
            "waveHeight": {
                "icon": 1.23,
                "noaa": 0.49,
                "sg": 1.23
            }
        },
        {
            "airTemperature": {
                "noaa": 13.22,
                "sg": 13.22
            },
            "time": "2023-01-24T01:00:00+00:00",
            "waveHeight": {
                "icon": 1.2,
                "noaa": 0.46,
                "sg": 1.2
            }
        },
        {
            "airTemperature": {
                "noaa": 12.78,
                "sg": 12.78
            },
            "time": "2023-01-24T02:00:00+00:00",
            "waveHeight": {
                "icon": 1.16,
                "noaa": 0.44,
                "sg": 1.16
            }
        },
        {
            "airTemperature": {
                "noaa": 12.34,
                "sg": 12.34
            },
            "time": "2023-01-24T03:00:00+00:00",
            "waveHeight": {
                "icon": 1.13,
                "noaa": 0.41,
                "sg": 1.13
            }
        },
        {
            "airTemperature": {
                "noaa": 12.33,
                "sg": 12.33
            },
            "time": "2023-01-24T04:00:00+00:00",
            "waveHeight": {
                "icon": 1.12,
                "noaa": 0.38,
                "sg": 1.12
            }
        },
        {
            "airTemperature": {
                "noaa": 12.31,
                "sg": 12.31
            },
            "time": "2023-01-24T05:00:00+00:00",
            "waveHeight": {
                "icon": 1.12,
                "noaa": 0.35,
                "sg": 1.12
            }
        }
    ],
    "meta": {
        "cost": 1,
        "dailyQuota": 1000,
        "end": "2023-01-24 05:59",
        "lat": 34.022,
        "lng": -118.831,
        "params": [
            "waveHeight",
            "airTemperature"
        ],
        "requestCount": 1,
        "start": "2023-01-23 06:00"
    }
}

In [10]:
print(json_data)

{'hours': [{'airTemperature': {'noaa': 10.67, 'sg': 10.67}, 'time': '2023-01-23T06:00:00+00:00', 'waveHeight': {'icon': 1.64, 'noaa': 0.56, 'sg': 1.64}}, {'airTemperature': {'noaa': 11.06, 'sg': 11.06}, 'time': '2023-01-23T07:00:00+00:00', 'waveHeight': {'icon': 1.66, 'noaa': 0.52, 'sg': 1.66}}, {'airTemperature': {'noaa': 11.44, 'sg': 11.44}, 'time': '2023-01-23T08:00:00+00:00', 'waveHeight': {'icon': 1.68, 'noaa': 0.49, 'sg': 1.68}}, {'airTemperature': {'noaa': 11.83, 'sg': 11.83}, 'time': '2023-01-23T09:00:00+00:00', 'waveHeight': {'icon': 1.7, 'noaa': 0.45, 'sg': 1.7}}, {'airTemperature': {'noaa': 11.51, 'sg': 11.51}, 'time': '2023-01-23T10:00:00+00:00', 'waveHeight': {'icon': 1.69, 'noaa': 0.45, 'sg': 1.69}}, {'airTemperature': {'noaa': 11.19, 'sg': 11.19}, 'time': '2023-01-23T11:00:00+00:00', 'waveHeight': {'icon': 1.69, 'noaa': 0.44, 'sg': 1.69}}, {'airTemperature': {'noaa': 10.88, 'sg': 10.88}, 'time': '2023-01-23T12:00:00+00:00', 'waveHeight': {'icon': 1.68, 'noaa': 0.44, 'sg': 1.68}}, {'airTemperature': {'noaa': 10.72, 'sg': 10.72}, 'time': '2023-01-23T13:00:00+00:00', 'waveHeight': {'icon': 1.64, 'noaa': 0.43, 'sg': 1.64}}, {'airTemperature': {'noaa': 10.56, 'sg': 10.56}, 'time': '2023-01-23T14:00:00+00:00', 'waveHeight': {'icon': 1.6, 'noaa': 0.41, 'sg': 1.6}}, {'airTemperature': {'noaa': 10.4, 'sg': 10.4}, 'time': '2023-01-23T15:00:00+00:00', 'waveHeight': {'icon': 1.56, 'noaa': 0.4, 'sg': 1.56}}, {'airTemperature': {'noaa': 11.2, 'sg': 11.2}, 'time': '2023-01-23T16:00:00+00:00', 'waveHeight': {'icon': 1.52, 'noaa': 0.39, 'sg': 1.52}}, {'airTemperature': {'noaa': 12.0, 'sg': 12.0}, 'time': '2023-01-23T17:00:00+00:00', 'waveHeight': {'icon': 1.48, 'noaa': 0.37, 'sg': 1.48}}, {'airTemperature': {'noaa': 12.79, 'sg': 12.79}, 'time': '2023-01-23T18:00:00+00:00', 'waveHeight': {'icon': 1.44, 'noaa': 0.36, 'sg': 1.44}}, {'airTemperature': {'noaa': 13.43, 'sg': 13.43}, 'time': '2023-01-23T19:00:00+00:00', 'waveHeight': {'icon': 1.41, 'noaa': 0.36, 'sg': 1.41}}, {'airTemperature': {'noaa': 14.07, 'sg': 14.07}, 'time': '2023-01-23T20:00:00+00:00', 'waveHeight': {'icon': 1.39, 'noaa': 0.36, 'sg': 1.39}}, {'airTemperature': {'noaa': 14.7, 'sg': 14.7}, 'time': '2023-01-23T21:00:00+00:00', 'waveHeight': {'icon': 1.36, 'noaa': 0.36, 'sg': 1.36}}, {'airTemperature': {'noaa': 14.36, 'sg': 14.36}, 'time': '2023-01-23T22:00:00+00:00', 'waveHeight': {'icon': 1.32, 'noaa': 0.4, 'sg': 1.32}}, {'airTemperature': {'noaa': 14.01, 'sg': 14.01}, 'time': '2023-01-23T23:00:00+00:00', 'waveHeight': {'icon': 1.27, 'noaa': 0.45, 'sg': 1.27}}, {'airTemperature': {'noaa': 13.66, 'sg': 13.66}, 'time': '2023-01-24T00:00:00+00:00', 'waveHeight': {'icon': 1.23, 'noaa': 0.49, 'sg': 1.23}}, {'airTemperature': {'noaa': 13.22, 'sg': 13.22}, 'time': '2023-01-24T01:00:00+00:00', 'waveHeight': {'icon': 1.2, 'noaa': 0.46, 'sg': 1.2}}, {'airTemperature': {'noaa': 12.78, 'sg': 12.78}, 'time': '2023-01-24T02:00:00+00:00', 'waveHeight': {'icon': 1.16, 'noaa': 0.44, 'sg': 1.16}}, {'airTemperature': {'noaa': 12.34, 'sg': 12.34}, 'time': '2023-01-24T03:00:00+00:00', 'waveHeight': {'icon': 1.13, 'noaa': 0.41, 'sg': 1.13}}, {'airTemperature': {'noaa': 12.33, 'sg': 12.33}, 'time': '2023-01-24T04:00:00+00:00', 'waveHeight': {'icon': 1.12, 'noaa': 0.38, 'sg': 1.12}}, {'airTemperature': {'noaa': 12.31, 'sg': 12.31}, 'time': '2023-01-24T05:00:00+00:00', 'waveHeight': {'icon': 1.12, 'noaa': 0.35, 'sg': 1.12}}], 'meta': {'cost': 1, 'dailyQuota': 1000, 'end': '2023-01-24 05:59', 'lat': 34.022, 'lng': -118.831, 'params': ['waveHeight', 'airTemperature'], 'requestCount': 1, 'start': '2023-01-23 06:00'}}